# Tensorflow Basics

In [1]:
import tensorflow as tf

In [37]:
print(tf.__version__)

2.1.0


# Tensors

In [38]:
 with tf.compat.v1.Session() as ses:

     # Build a graph.
     a = tf.constant('hello')
     b = tf.constant(' world')
     c = a + b

     # Evaluate the tensor `c`.
     print(ses.run(c))

b'hello world'


# Computaion

In [39]:
tensor_1=tf.constant(1)

In [40]:
tensor_2=tf.constant(2)


In [41]:
type(tensor_1)

tensorflow.python.framework.ops.EagerTensor

In [42]:
tensor_1+tensor_2

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [43]:
sess

In [44]:
sess.close()

# Operstions

In [45]:
 with tf.compat.v1.Session() as sess:
     # Build a graph.
    const= tf.constant(10)
    fill_mat=tf.fill((4,4),10)
    myzeros=tf.zeros((4,4))
    myones=tf.ones((4,4))
    myrandn = tf.random.normal((4,4),mean=0,stddev=0.5)
    myrandu=tf.random.uniform((4,4),minval=0,maxval=1)
    my_ops=[const,fill_mat,myzeros,myones,myrandn,myrandu]
    
#      # Evaluate the tensor `c`.
    print(sess.run(my_ops))

[10, array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]]), array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32), array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32), array([[-0.5624514 ,  0.25319025,  0.46524906,  0.65039027],
       [-0.00863954,  0.16162272,  0.02339307, -1.3333526 ],
       [-0.22379048, -0.36562687,  0.19271621,  0.0665229 ],
       [-0.20983842, -0.03629819,  0.12442094,  0.26573274]],
      dtype=float32), array([[0.6552857 , 0.8415773 , 0.35882688, 0.3827268 ],
       [0.75028133, 0.70015943, 0.6617197 , 0.58948696],
       [0.19950247, 0.7929313 , 0.34533715, 0.27321088],
       [0.90711   , 0.72263956, 0.57768166, 0.46497083]], dtype=float32)]


# Interactive Sesion

In [1]:
sess=tf.compat.v1.InteractiveSession()

NameError: name 'tf' is not defined

In [47]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.0470074  -0.18420506 -0.14491712  0.17573678]
 [ 0.16572647  0.22692192  0.06310394 -0.40264022]
 [ 0.03442502 -0.5315209   0.4784892  -0.58203894]
 [-1.1275481   0.42726982  0.47948307  0.09048431]]


[[0.02721405 0.03748739 0.86020446 0.8878267 ]
 [0.33845758 0.94689703 0.13520145 0.7356621 ]
 [0.87780297 0.5817944  0.44064522 0.4631362 ]
 [0.9384483  0.11416185 0.05448401 0.45328188]]




In [48]:
my_ops

[<tf.Tensor 'Const_7:0' shape=() dtype=int32>,
 <tf.Tensor 'Fill_3:0' shape=(4, 4) dtype=int32>,
 <tf.Tensor 'zeros_3:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'ones_3:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_normal_3:0' shape=(4, 4) dtype=float32>,
 <tf.Tensor 'random_uniform_3:0' shape=(4, 4) dtype=float32>]

# Matrix Multiplication

In [49]:
with tf.compat.v1.Session() as sess:
    a=tf.constant([[1,2],[3,4]])
    b=tf.constant([[10],[100]])
    result=tf.matmul(a,b)
        
        
        
#     const= tf.constant(10)
#     fill_mat=tf.fill((4,4),10)
#     myzeros=tf.zeros((4,4))
#     myones=tf.ones((4,4))
#     myrandn = tf.random.normal((4,4),mean=0,stddev=0.5)
#     myrandu=tf.random.uniform((4,4),minval=0,maxval=1)
#     my_ops=[const,fill_mat,myzeros,myones,myrandn,myrandu]
    
#      # Evaluate the tensor `c`.
#     print(sess.run(result))

In [50]:
result.eval()

array([[210],
       [430]])

# 1. TF Graph

In [51]:
import tensorflow as tf

In [59]:
with tf.compat.v1.Session() as sess:
    n1=tf.constant(1)
    n2=tf.constant(2)
    n3=tf.add(n1,n2)
    result=sess.run(n3)

In [60]:
print(result)

3


In [61]:
print(n3)

Tensor("Add_1:0", shape=(), dtype=int32)


In [63]:
print(tf.compat.v1.get_default_graph())

In [64]:
g=tf.Graph()

In [65]:
print(g)

In [67]:
graph_one=tf.compat.v1.get_default_graph()

In [68]:
print(graph_one)

In [69]:
graph_two=tf.Graph()

In [70]:
print(graph_two)

In [73]:
with graph_two.as_default():
    print(graph_two is tf.compat.v1.get_default_graph())

True


In [74]:
print(graph_two is tf.compat.v1.get_default_graph())

False


# 2. TF Graph

In [2]:
import tensorflow as tf

In [16]:
sess=tf.compat.v1.Session()

In [17]:
my_tensor=tf.compat.v1.random_uniform((4,4),0,1)

In [18]:
my_tensor

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.69250727, 0.67730665, 0.34447253, 0.7981535 ],
       [0.29544783, 0.8495413 , 0.5492594 , 0.3745427 ],
       [0.99444926, 0.36341572, 0.94176626, 0.34534776],
       [0.05513406, 0.9116837 , 0.15252233, 0.00792146]], dtype=float32)>

In [19]:
my_var=tf.compat.v1.Variable(initial_value=my_tensor)

In [20]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[0.69250727, 0.67730665, 0.34447253, 0.7981535 ],
       [0.29544783, 0.8495413 , 0.5492594 , 0.3745427 ],
       [0.99444926, 0.36341572, 0.94176626, 0.34534776],
       [0.05513406, 0.9116837 , 0.15252233, 0.00792146]], dtype=float32)>


In [22]:
init=tf.compat.v1.global_variables_initializer()

In [23]:
sess.run(init)

RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

In [189]:
with tf.compat.v1.InteractiveSession() as sess:
    my_tensor=tf.compat.v1.random_uniform((4,4),0,1)
    my_var=tf.Variable(initial_value=my_tensor)
    init=tf.compat.v1.global_variables_initializer()
#     sess.run(init)
    

C:\Users\Himanshu\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\client\session.py:1752: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


AttributeError: __enter__

In [127]:
sess.close()

In [211]:
r=sess.run(my_var)

AttributeError: Tensor.graph is meaningless when eager execution is enabled.

In [136]:
loss = sess.run(loss)

NameError: name 'loss' is not defined

In [145]:
init


In [146]:
print(init)

None


In [159]:
type(my_var)

tensorflow.python.framework.ops.EagerTensor

In [210]:
my_var=tf.convert_to_tensor(
    my_var, dtype=None, dtype_hint=None, name=None
)

In [180]:
print(sess)

In [212]:
init= tf.compat.v1.global_variables_initializer()

# Launch the graph in a session.
with tf.compat.v1.Session() as sess:
    # Run the Op that initializes global variables.
    sess.run(init)
    # ...you can now run any O

TypeError: Fetch argument None has invalid type <class 'NoneType'>

In [213]:
sess = tf.compat.v1.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
# We can just use 'c.eval()' without passing 'sess'
print(c.eval())
sess.close()

C:\Users\Himanshu\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\client\session.py:1752: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


NotImplementedError: eval is not supported when eager execution is enabled, is .numpy() what you're looking for?

In [11]:
init=tf.compat.v1.global_variables_initializer()

In [24]:
with tf.compat.v1.Session() as sess:
    
    sess.run(init)

RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().